name: powerplatform-actions
uses: microsoft/powerplatform-actions@v0.9.1
  with:
    name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0.9.1
        with:
          solution-file: ${{ github.workspace }}/repo/CoEKit-Production/CoEStarterKit_Unmanaged.zip
          solution-folder: ${{ github.workspace }}/repo/CoEKit-Production/Aug22
          solution-type: 'Unmanaged'
          overwrite-files: true
