name: commit-coekit-prod-core
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'CoEKit Production solution package name'
        required: true
        default: Dummy
      solution_version:
        description: 'CoEKit Production solution package version'
        required: true
        default: August2022

jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
              
      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0.9.1
        with:
          solution-file: CoEKit-Production/${{ github.event.inputs.solution_name }}
          solution-folder: CoEKit-Production/temp
          solution-type: 'Unmanaged'
          overwrite-files: true
          
      - name: branch-solution, prepare it for a PullRequest
        uses: microsoft/powerplatform-actions/branch-solution@v0.9.1
        with:
          solution-folder: CoEKit-Production/temp
          solution-target-folder: CoEKit-Production/${{ github.event.inputs.solution_version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
