name: commit-coekit-prod-core
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'CoEKit Production solution package name'
        required: true
        default: Dummy
      solution_version:
        description: 'CoEKit Production solution package version'
        required: true
        default: August2022

jobs:
  commit-coekit-prod-core:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
              
      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0.9.1
        with:
          solution-file: coekit-prod-core/${{ github.event.inputs.solution_name }}
          solution-folder: coekit-prod-core/temp/${{ github.event.inputs.solution_version }}
          solution-type: 'Unmanaged'
          overwrite-files: true
      
      - name: Format JSON
        run: |
          gci -Path coekit-prod-core/temp/${{ github.event.inputs.solution_version }} -Filter *.json -Recurse | % { gc -Path $_.FullName -Raw | ConvertFrom-Json | ConvertTo-Json -Depth 100 | Set-Content -Path $_.FullName }
        shell: pwsh
        
      - name: branch-solution, prepare it for a PullRequest
        uses: microsoft/powerplatform-actions/branch-solution@v0.9.1
        with:
          solution-folder: coekit-prod-core/temp/${{ github.event.inputs.solution_version }}
          solution-target-folder: coekit-prod-core/${{ github.event.inputs.solution_version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
